service: cupido-api

package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  - serverless-dotenv-plugin 

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:service}-messages

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

 
  environment:
    tableName: ${self:custom.tableName}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     
      Resource:
        - "Fn::GetAtt": [ MessagesTable, Arn ]

functions:
  - ${file(functions/create/create-function.yml)}
  - ${file(functions/delete/delete-function.yml)}
  - ${file(functions/email/email-function.yml)}
  - ${file(functions/get/get-function.yml)}
  - ${file(functions/list/list-function.yml)}
  - ${file(functions/update/update-function.yml)}

resources: 
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  



